# Generated by Django 2.2.5 on 2019-09-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='timeframe',
            field=models.IntegerField(choices=[(1, 'M1'), (16386, 'H1')], default=1),
        ),
    ]
